// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWACZ_aRVGWlFeptSK2RvyrDZrLdsFJqk',
    appId: '1:908797335681:web:3e6d464dd055b521605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    authDomain: 'fir-meal-99bca.firebaseapp.com',
    storageBucket: 'fir-meal-99bca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlhAbiEI8JhJvfDhizO8cWkcoYf4P_qFE',
    appId: '1:908797335681:android:56eae728d01bad61605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    storageBucket: 'fir-meal-99bca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLBv1nTWDHj84qm3CqwHR2fR4wpKTDl-s',
    appId: '1:908797335681:ios:7f6fd213e11a312f605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    storageBucket: 'fir-meal-99bca.appspot.com',
    iosClientId: '908797335681-5vm98d1q2r3o6v779deaqi3grsfpan6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLBv1nTWDHj84qm3CqwHR2fR4wpKTDl-s',
    appId: '1:908797335681:ios:7f6fd213e11a312f605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    storageBucket: 'fir-meal-99bca.appspot.com',
    iosClientId: '908797335681-5vm98d1q2r3o6v779deaqi3grsfpan6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoMeal',
  );
}
